### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by MonsieurNaexec** [paaull/REST_API_Framework#1]
This is not really an issue, but I just wonder why you say that it is not for production? Is it a security problem?

**Comment by paaull** [comment]
Hey, thanks for your question. This was just a bit of fun back when I was learning PHP. I just mentioned that it's not for production use as there's far better frameworks out there being actively managed (perhaps Laravel, Slim, etc), so I'd never really use this for production code.

**Comment by MonsieurNaexec** [comment]
Ok, thanks. In fact, I like this project because it does not require to install any packages or framework with composer.
